### ISSUE TITLE
[Arbo] Création de branches impossibles

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#170]
### Fonctionnement constaté
J'ai crée une nouvelle connaissance dans l'arbo, mais je ne peux pas créer de branches supplémentaires. 
Idem lorsque l'arbre a déjà une branche, je ne peux pas créer ou voir les sous-branches supplémentaires

### Fonctionnement souhaité
Il faudrait que je puisse créer une branche à une nouvelle connaissance et que je puisse créer des branches à un arbre déjà existant

**Comment by vincentlaine** [comment]
Hmmm en fait le problème c'est que le bouton "+" viens rajouter un choix à une réponse à choix.

Sauf que quand y'a pas de réponse à choix je fait comment, je rajoute quand même le "+" mais ça ouvre la fenêtre d'édition ?

**Comment by linnataing** [comment]
Au clic sur le +, j'ai bien deux propositions  : soit j'ajoute une connaissance existante, soit je crée une nouvelle connaissance, mais c'est impossible de continuer, car j'ai un message d'erreur qui s'affiche systématiquement : 
<img width="1253" alt="Capture d’écran 2021-06-14 à 14 07 45" src="https://user-images.githubusercontent.com/63412351/121890164-54c56b00-cd1a-11eb-835c-8aab35371846.png">

**Comment by linnataing** [comment]
Yes, ca peut être une idée, d'ouvrir directement la fenetre d'édition dans le cas où il n'y a pas déjà de réponse à choix
