### ISSUE TITLE
[Arbo] Ajout d'une connaissance existante > Filtre catégorie K.O

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#174]
### Fonctionnement constaté
Lorsque j'ajoute une connaissance existante et je trie selon les catégories, l'affichage des questions ne se change pas. J'ai toujours la liste par défaut de toutes les questions.
![Capture d’écran 2021-06-01 à 09 26 02](https://user-images.githubusercontent.com/63412351/120283772-d5687e00-c2bb-11eb-8dcf-68cf76ebb394.png)

### Fonctionnement souhaité 
Il faudrait que l'affichage de la liste des questions puisse être fonction de la catégorie sélectionnée

**Comment by vincentlaine** [comment]
J'arrive pas à le refaire, de mon côté ça fonctionne.
