### ISSUE TITLE
[BO-Stats] Nouvelles pages stats F.A.Q + Feedbacks

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#187]
Dans la page Stats, il faudrait pouvoir accéder aux stats F.A.Q et aux stats liés aux feedbacks utilisateurs. 

La page F.A.Q est constituée : 
- des questions les plus consultées --> graphique + liste
- des catégories les plus consultées --> graphique + liste
des indicateurs : 
- nb de consultation de la F.A.Q
- nb moyen de questions consultées par visiteur

La page Feedback est constituée : 
- d'un volet (refermable) Réponses notées comme étant pertinente  (2 graphiques : liste des réponses + liste des catégories)
- d'un volet (refermable) Réponses notées comme étant erronées (2 graphiques : liste des réponses + liste des catégories)
- d'un volet (refermable) Réponses notées comme “ne répondant pas à la question” (2 graphiques : liste des réponses + liste des catégories)
Des indicateurs : 
- → XX (en XX%) réponses indiquées comme étant pertinentes 
→ XX (en XX%) réponses indiquées comme étant erronées
→ XX (en XX%)  réponses indiquées comme “ne répondant pas à la question”

![FAQ](https://user-images.githubusercontent.com/63412351/125474432-c717fa41-3e1f-4a3d-ab74-7ccf0eba4771.jpg)
![FEEDBACKS](https://user-images.githubusercontent.com/63412351/125476483-51068833-e153-4fd1-8794-fb0c306aacc5.jpg)

**Comment by vincentlaine** [comment]
Page FAQ done, manque le feedback !

La librairie de graph a été upgradée également d'où le léger changement graphique.
