### ISSUE TITLE
[Bug arbo] Tous les liens n'apparaissent pas

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#188]
**Comportement constaté**
Emilie de la RH marine vient de me remonter un bug sur cette question : 
--> Qu'est-ce que le BST ?
Dans connaissances > liste > puis visualisation de la petite arbo, on voit qu'il y a 3 /s questions 
Mais quand on consulte la grande arborescence, on n'en voit que 2. La question liée : Comment se déroule l'avancement d'un BST ? ne s'affiche pas.

D'ailleurs quand on clique dessus, il y a une erreur interne.
Est-ce que tu pourrais regarder ce qui ne va pas sur cette question stp ? 

![BUG_BST](https://user-images.githubusercontent.com/63412351/126186323-0252a89b-f932-42c8-9b0e-28b8a67025a2.png)
<img width="1041" alt="Capture d’écran 2021-07-19 à 17 20 26" src="https://user-images.githubusercontent.com/63412351/126186335-5c06e281-51df-43d0-b3c0-ef3ab0dc3c2f.png">
<img width="1271" alt="Capture d’écran 2021-07-19 à 17 29 46" src="https://user-images.githubusercontent.com/63412351/126186339-774e845c-a9d1-4384-805f-b4855355ee76.png">

**Comment by vincentlaine** [comment]
En fait ils avaient du importer une réponse à choix via l'excel avec un ancien ID et donc ça le remontait pas, j'ai mit à jour la réponse via le BO et tout roule :)
