### ISSUE TITLE
Odinors - https K.O 

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#191]
https://odinors.chatbot.fabnum.fr/chatbot

Je n'arrive plus à accéder au site Odinors, j'ai un message : 

Votre connexion n'est pas privée
Des individus malveillants tentent peut-être de subtiliser vos informations personnelles sur le site odinors.chatbot.fabnum.fr (mots de passe, messages ou numéros de carte de crédit, par exemple). En savoir plus
NET::ERR_CERT_DATE_INVALID

**Comment by vincentlaine** [comment]
Rha fuck, j'ai résolu le problème à la mano mais ça vient d'un port que j'ai fermé suite au comité SC2A et donc le certificat peut pas se renouveler tout seul ...

Je vais voir avec Manon si y'a moyen de laisser le port ouvert sur internet vu que le SC2A est censé s'occuper que d'intradef.
