### ISSUE TITLE
[Requêtes] Disparition des assignations 

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#196]
Ce matin que constate que plus aucune question n’est « assignée » alors que les ¾ d’entre elles l’étaient. En soit ce n’est pas très grave je vais le refaire mais je souhaitais quand même te faire remonter l’info.

**Comment by vincentlaine** [comment]
J'ai rien trouvé de bizarre dans les logs donc je voit pas trop comment ça a pu arriver. En tout cas personne n'a "désassigner" des requêtes dans le weekend.
En checkant les logs j'ai vu qu'Emilie n'avais assignée qu'une seule requête depuis Lundi matin et pourtant y'en a pas mal qui sont assignée dans le backoffice. Je pencherais peut être plus sur un bug ponctuel du Front (genre la liste des users qui a pas chargée ?) qui a fait foirer l'affichage des assignations.
