### ISSUE TITLE
[Réponse du bot] affichage du message d'accueil quand réponse non pertinente

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#240]
Je ne sais pas si qq chose a changé avec l'implémentation de la rép. par défaut "phrase_hors_sujet", mais maintenant quand on tape n'importe quoi ex : hdildkpce, au lieu d'afficher la phrase par défaut, j'ai l'affichage de la phrase de bienvenue. 
<img width="957" alt="Capture d’écran 2022-05-09 à 14 49 11" src="https://user-images.githubusercontent.com/63412351/167413212-2ddb6bef-f696-4216-a792-f5aca2c339e0.png">

**Comment by vincentlaine** [comment]
je reproduit plus le bug
