### ISSUE TITLE
[Import de la base de connaissance] Bug sur des urls lors import bdd

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#245]
### Fonctionnement constaté
Ma base de connaissance initiale est celle-ci :
[base_connaissance-initiale.xlsx](https://github.com/fabnumdef/chatbot-front/files/8942348/base_connaissance-initiale.xlsx)
- j'ai remplacé l'url ci-dessous par la suivante : 
<img width="1053" alt="Capture d’écran 2022-06-20 à 18 37 41" src="https://user-images.githubusercontent.com/63412351/174646764-cfbea17d-d12d-4835-8f81-c21725a28581.png">
ce qui me donne le fichier suivant : <br>

[base_connaissance-modifiee.xlsx](https://github.com/fabnumdef/chatbot-front/files/8942451/base_connaissance-modifiee.xlsx)

----
Quand je compare les deux bases avant après, j'ai une modification qui a bien été effectuée mais j'ai aussi 2 ratés : 
- "sur le site Eureka : <https://eureka.intradef.gouv.fr/#/catalogue/fiche/14801>" qui a été transformé en :
" sur le site Eureka : <https://fab-chatbot-rh-marine.intradef.gouv.fr//>"

- "Voici le lien pour accéder directement au site : <https://ensap.gouv.fr/web/accueilnonconnecte>" qui a été transformé en : "Voici le lien pour accéder directement au site : <https://fab-chatbot-rh-marine.intradef.gouv.fr//web/accueilnonconnecte>"

### Fonctionnement souhaité
Il ne faudrait pas que les urls correctes de portails soient modifiées

**Comment by vincentlaine** [comment]
Effectivement y'avait un pti bug sur la détection d'URL, c'est déployé et à tester :)

**Comment by linnataing** [comment]
NIquel !! C'est bon pour moi ;) Merci Vincent
