### ISSUE TITLE
[Chatbot] Application de la charte sur le chatbot

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#252]
Application de la charte de l'état sur les bots générés par l'usine à chatbots
[Les MAQUETTES MOBILE sont ici](https://drive.google.com/file/d/1AEwxuZ-ylgO_OPQGdMVM2h94qP0S1fuM/view?usp=sharing)
 
🛑 NB : Vincent, si tu attaques ce ticket, est-ce que tu pourras me prévenir stp ? 
Il faut que je fasse un mail pour tous les porteurs qui ont un bot Internet, du changement qui va arriver et les prévenir de la date du déploiement en prod !

**Comment by vincentlaine** [comment]
J'attaque le ticket ! Mais ce serait déployé que pour chaque bot au cas par cas. Tu me diras quand le dpéloyer en prod.

**Comment by linnataing** [comment]
Ok, c'est bon tous les utilisateurs sont prévenus :) 
Ca peut intervenir avant fin juillet quand tu veux / peux

**Comment by vincentlaine** [comment]
Déployé sur dev & demo
