### ISSUE TITLE
[Ajout utilisateur] url de création de compte incomplète

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#255]
**Fonctionnement constaté :**
Sur le bot [](https://avt-georges.chatbot.fabnum.fr/chatbot/) : 

1.       Lors du process de création de compte : le mail générer vers l’utilisateur contient une URL d’activation incomplète : « https:\\avt-georges\chatbot\... » au lieu de « https:\\[avt-georges.chatbot.fabnum.fr](http://avt-georges.chatbot.fabnum.fr/)\chatbot\... », impossible donc pour l'utilisateur de se connecter pour se créer son compte s'il ne connait pas l'url

**Comment by vincentlaine** [comment]
Effectivement y'avait une variable d'environnement qui était mal initialisée (je sais pas pq)
