### ISSUE TITLE
Import/Export connaissances : disparu ?

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#33]
Que s'est-il passé ? 
La fonctionnalité d'import/export des connaissances a disparu de la plateforme ?
<img width="1248" alt="Capture d’écran 2020-06-09 à 19 07 01" src="https://user-images.githubusercontent.com/63412351/84178384-a17dc280-aa84-11ea-964d-01e8b3cad2e9.png">

**Comment by vincentlaine** [comment]
Héhéhé, j'ai mit à jour les droits.

Chat bot est contributeur, faut se loguer avec admin@fabnum.fr pour avoir accès à l'import / export ;)
