### ISSUE TITLE
INBOX > masquer les remontées 

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#37]
Remontées de Julia, sur les quelques tests qu'elle a réalisé : est-ce possible de masquer les questions qui sont 100% correctes ou qui ont un accent en plus / moins ? Les mettre en en corrects par défaut.
<img width="787" alt="Capture d’écran 2020-06-11 à 16 42 07" src="https://user-images.githubusercontent.com/63412351/84400852-dadc3c80-ac02-11ea-9152-a671d59b9f9c.png">

**Comment by vincentlaine** [comment]
J'ai rajouté un check, si la confiance est à plus de 95%, ça apparait pas.
