### ISSUE TITLE
Réponse image > Affichage KO dans le bot

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#41]
Dans ma réponse j'ai une image qui s'affiche bien dans le BO, mais pas en front dans le bot : 
<img width="769" alt="Capture d’écran 2020-06-11 à 17 38 31" src="https://user-images.githubusercontent.com/63412351/84409422-b2a60b00-ac0d-11ea-838a-61e2086da47e.png">
<img width="1098" alt="Capture d’écran 2020-06-11 à 17 38 40" src="https://user-images.githubusercontent.com/63412351/84409425-b33ea180-ac0d-11ea-9827-e8344570eef1.png">

**Comment by vincentlaine** [comment]
Hmmm moi ça marche bien

![image](https://user-images.githubusercontent.com/3847924/84500664-4e3e8680-acb5-11ea-9ae6-fd116f7e51c9.png)
