### ISSUE TITLE
Médiathèque > jauge fonctionnalle ?

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#51]
Est-ce que la jauge est fonctionnelle ? 
Il y a quelques fichiers en BO mais elle affiche toujours 0 en remplissage 
<img width="1263" alt="Capture d’écran 2020-06-12 à 15 04 47" src="https://user-images.githubusercontent.com/63412351/84505544-2bfd3680-acbe-11ea-84cf-3f413ea8efb8.png">

**Comment by vincentlaine** [comment]
Yep yep, c'est juste que les fichiers sont super petits et donc ça fait même pas 0,01Go (10Mo)
