### ISSUE TITLE
Connaissances > Suppression maintient catégorie

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#68]
Lorsqu'une connaissance est supprimée et que la catégorie associée ne comporte plus de connaissances, la catégorie reste et on ne peut pas la supprimer. 
Il faudrait la supprimer et qu'elle ne s'affiche plus dans les filtres de recherche.

**Comment by vincentlaine** [comment]
Sur ta vidéo la connaissance à laquelle tu l'as liée est "Qu'est ce que la VAE ?" et après dans l'écran de connaissance tu as regardée "Quelle est l'utilité de la VAE dans le civil ?"

**Comment by linnataing** [comment]
My bad pour la capture d'écran associée à la mauvaise connaissance ! Jsais pas ou était ma tete. J'ai testé en créant une nouvelle catégorie ce matin, ca fonctionne niquel, merci !
