### ISSUE TITLE
Inbox > Questions liées - pas d'ajout dans les questions synonymes

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#69]
C'est moi qui ai pas compris le fonctionnement de l'inbox ? Ou c'est un bug ? 
Quand je clique sur la connaissance liée dans INBOX, la question liée est censée s'incrémenter aux questions synonymes de la connaissance non ?

https://www.loom.com/share/4d6d92d972744a22b3e79aeb2a3debce

**Comment by vincentlaine** [comment]
Sur ta vidéo la connaissance à laquelle tu l'as liée est "Qu'est ce que la VAE ?" et après dans l'écran de connaissance tu as regardée "Quelle est l'utilité de la VAE dans le civil ?"
