### ISSUE TITLE
[Stats] Questions les plus posées - masquer questions hors sujet

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/chatbot-front#83]
Dans la section questions les plus posées, un point apparait sans question. Il faudrait masquer ou supprimer l'affichage des questions hors sujet.

**Comment by vincentlaine** [comment]
@Matthieu-R dans la requête SQL, exclure les questions qui sont `phrase_presentation`, `phrase_hors_sujet` et `phrase_feedback`
